import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1F1F1F",
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 30,
  },
  headerRow: {
    position: "relative",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "nowrap",
    rowGap: 12,
    marginBottom: 28,
    paddingRight: 110,
  },
  headerTextBlock: {
    flex: 1,
    minWidth: 0,
    paddingRight: 6,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  brandIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "rgba(76, 175, 80, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  brandText: {
    color: "#16A34A",
    fontSize: 24,
    fontWeight: "800",
  },
  greeting: {
    color: "#F9FAFB",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 4,
  },
  heading: {
    color: "#F9FAFB",
    fontSize: 26,
    fontWeight: "900",
    lineHeight: 32,
  },
  topIcons: {
    position: "absolute",
    top: 0,
    right: 0,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 22,
    backgroundColor: "#2A2A2A",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  searchButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#2A2A2A",
    justifyContent: "center",
    alignItems: "center",
  },
  sectionCard: {
    width: width * 0.88,
    backgroundColor: "#2A2A2A",
    borderRadius: 18,
    padding: 12,
    marginBottom: 22,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  horizontalList: {
    paddingBottom: 4,
  },
  mapHeader: {
    marginBottom: 14,
  },
  mapLabel: {
    color: "#F9FAFB",
    fontSize: 16,
    fontWeight: "700",
  },
  mapSubLabel: {
    color: "#C7C7C7",
    fontSize: 14,
    marginTop: 4,
  },
  mapSectionCard: {
    backgroundColor: "#2A2A2A",
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    marginBottom: 16,
  },
  mapPlaceholder: {
    height: 220,
    borderRadius: 18,
    backgroundColor: "#333333",
    overflow: "hidden",
    marginTop: 10,
  },
  map: {
    width: "100%",
    height: "100%",
  },
  mapPlaceholderText: {
    color: "#C7C7C7",
    fontSize: 14,
    position: "absolute",
    bottom: 16,
  },
  pinRow: {
    width: "100%",
    height: "100%",
  },
  pin1: {
    position: "absolute",
    top: "26%",
    left: "42%",
  },
  pin2: {
    position: "absolute",
    top: "45%",
    left: "28%",
  },
  pin3: {
    position: "absolute",
    top: "60%",
    left: "60%",
  },
  searchBoxContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#2A2A2A",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.22)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 14,
  },
  searchInput: {
    flex: 1,
    color: "#F9FAFB",
    fontSize: 14,
    fontWeight: "500",
  },
  sectionHeader: {
    marginBottom: 10,
    marginTop: 8,
  },
  sectionTitle: {
    color: "#F9FAFB",
    fontSize: 18,
    fontWeight: "800",
  },
  sectionSubtitle: {
    color: "#C7C7C7",
    fontSize: 13,
    marginTop: 4,
  },
  cardList: {
    paddingVertical: 8,
  },
  card: {
    width: width * 0.72,
    marginRight: 12,
    borderRadius: 16,
    backgroundColor: "#2A2A2A",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#3A3A3A",
  },
  cardImage: {
    width: "100%",
    height: 120,
    justifyContent: "flex-end",
  },
  cardImageInner: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  cardBadge: {
    alignSelf: "flex-start",
    margin: 12,
    backgroundColor: "rgba(76, 175, 80, 0.95)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  favoriteChip: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 3,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(17, 24, 39, 0.78)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    justifyContent: "center",
    alignItems: "center",
  },
  favoriteChipActive: {
    backgroundColor: "rgba(34, 197, 94, 0.18)",
    borderColor: "rgba(34, 197, 94, 0.55)",
  },
  favoriteChipBottom: {
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    borderRadius: 999,
    padding: 6,
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.35)",
  },
  cardBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  cardContent: {
    padding: 14,
  },
  cardTitle: {
    color: "#F9FAFB",
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 10,
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  cardRating: {
    color: "#F9FAFB",
    fontSize: 14,
    fontWeight: "700",
    marginLeft: 6,
  },
  cardDistance: {
    color: "#C7C7C7",
    fontSize: 14,
    fontWeight: "500",
  },
  detailButton: {
    backgroundColor: "#22C55E",
    borderRadius: 18,
    paddingVertical: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  detailButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  avatarContainer: {
    position: "relative",
    zIndex: 20,
    elevation: 20,
    alignSelf: "flex-end",
  },
  dropdownMenu: {
    position: "absolute",
    top: 50,
    right: 0,
    left: "auto",
    width: Math.min(width * 0.72, 220),
    maxWidth: width - 18,
    backgroundColor: "#2A2A2A",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#3A3A3A",
    paddingVertical: 8,
    paddingHorizontal: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 30,
    zIndex: 30,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 10,
  },
  menuItemText: {
    color: "#F9FAFB",
    fontSize: 15,
    fontWeight: "600",
  },
  menuDivider: {
    height: 1,
    backgroundColor: "#3A3A3A",
    marginVertical: 4,
  },
  smallCard: {
    flexDirection: "row",
    backgroundColor: "#252525",
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  horizontalCard: {
    position: "relative",
    width: width * 0.82,
    marginRight: 12,
    flexDirection: "column",
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#252525",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  horizontalCardImage: {
    width: "100%",
    height: 110,
    resizeMode: "cover",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  horizontalCardBody: {
    flex: 1,
    padding: 12,
    justifyContent: "space-between",
  },
  horizontalCardTitle: {
    color: "#F9FAFB",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 2,
  },
  horizontalCardMeta: {
    color: "#C7C7C7",
    fontSize: 12,
    marginTop: 2,
  },
  smallCardImage: {
    width: 92,
    height: 92,
  },
  smallCardBody: {
    flex: 1,
    padding: 10,
    justifyContent: "space-between",
  },
  smallCardTitle: {
    color: "#F9FAFB",
    fontSize: 14,
    fontWeight: "800",
  },
  smallCardMeta: {
    color: "#C7C7C7",
    fontSize: 12,
    marginTop: 2,
  },
  smallCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  smallCardDistance: {
    color: "#86EFAC",
    fontSize: 12,
    fontWeight: "700",
  },
  smallCardPrice: {
    color: "#22C55E",
    fontSize: 12,
    fontWeight: "800",
    flexShrink: 1,
  },
  statusPill: {
    color: "#F9FAFB",
    backgroundColor: "rgba(148,163,184,0.18)",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "700",
  },
  emptySection: {
    paddingVertical: 18,
    alignItems: "center",
  },
  emptySectionText: {
    color: "#C7C7C7",
    fontSize: 13,
    textAlign: "center",
    marginTop: 8,
  },
  bottomBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: "#1F1F1F",
    borderTopWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  bottomBarItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    paddingVertical: 8,
  },
  bottomBarItemActive: {
    backgroundColor: "rgba(76, 175, 80, 0.12)",
  },
  bottomBarText: {
    color: "#C7C7C7",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 4,
  },
  bottomBarTextActive: {
    color: "#16A34A",
  },
});
